language: python
python:
  - "2.7"
  # does not have headers provided, please ask https://launchpad.net/~pypy/+archive/ppa
  # maintainers to fix their pypy-dev package.
  - "pypy"
# command to install dependencies
env:
  - DJANGO_VERSION=1.8.2
install:
  - pip install -q Django==$DJANGO_VERSION
  - pip install -r requirements.txt
# command to run tests
script:
  - cp bojv4/scr_settings.py bojv4/secret_settings.py
  - python manage.py test
